<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Dota2VpkExtractor</AssemblyName>
    <RootNamespace>Dota2CosmeticDisabler.VpkExtractor</RootNamespace>
    <Version>0.3.2</Version>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ValvePak" Version="4.0.0.142" />
  </ItemGroup>
</Project>
