<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Dota2ModelSkinPatcher</AssemblyName>
    <RootNamespace>Dota2CosmeticDisabler.ModelPatcher</RootNamespace>
    <Version>0.4.0</Version>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ValveResourceFormat" Version="15.0.4937" />
  </ItemGroup>
</Project>
